# Generated by Django 5.0 on 2024-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpId',
            field=models.CharField(max_length=4),
        ),
    ]
